/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CollegeRouteImport } from './routes/college'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as CompanyIndexRouteImport } from './routes/company.index'
import { Route as CollegeIndexRouteImport } from './routes/college.index'
import { Route as StudentOpportunitiesRouteImport } from './routes/student.opportunities'
import { Route as StudentLearningRouteImport } from './routes/student.learning'
import { Route as StudentInternshipRouteImport } from './routes/student.internship'
import { Route as StudentDiscoverRouteImport } from './routes/student.discover'
import { Route as StudentApplicationsRouteImport } from './routes/student.applications'
import { Route as CompanyStudentsRouteImport } from './routes/company.students'
import { Route as CompanyOpportunitiesRouteImport } from './routes/company.opportunities'
import { Route as CompanyInternsRouteImport } from './routes/company.interns'
import { Route as CompanyCoursesRouteImport } from './routes/company.courses'
import { Route as CompanyAnalyticsRouteImport } from './routes/company.analytics'
import { Route as CollegeStudentsRouteImport } from './routes/college.students'
import { Route as CollegeInternshipsRouteImport } from './routes/college.internships'
import { Route as CollegeAnalyticsRouteImport } from './routes/college.analytics'
import { Route as StudentOpportunitiesIdRouteImport } from './routes/student.opportunities.$id'
import { Route as StudentCoursesIdRouteImport } from './routes/student.courses.$id'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeRoute = CollegeRouteImport.update({
  id: '/college',
  path: '/college',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanyRoute,
} as any)
const CollegeIndexRoute = CollegeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollegeRoute,
} as any)
const StudentOpportunitiesRoute = StudentOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLearningRoute = StudentLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => StudentRoute,
} as any)
const StudentInternshipRoute = StudentInternshipRouteImport.update({
  id: '/internship',
  path: '/internship',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDiscoverRoute = StudentDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => StudentRoute,
} as any)
const StudentApplicationsRoute = StudentApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => StudentRoute,
} as any)
const CompanyStudentsRoute = CompanyStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyOpportunitiesRoute = CompanyOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyInternsRoute = CompanyInternsRouteImport.update({
  id: '/interns',
  path: '/interns',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyCoursesRoute = CompanyCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyAnalyticsRoute = CompanyAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CompanyRoute,
} as any)
const CollegeStudentsRoute = CollegeStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => CollegeRoute,
} as any)
const CollegeInternshipsRoute = CollegeInternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => CollegeRoute,
} as any)
const CollegeAnalyticsRoute = CollegeAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CollegeRoute,
} as any)
const StudentOpportunitiesIdRoute = StudentOpportunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentOpportunitiesRoute,
} as any)
const StudentCoursesIdRoute = StudentCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/college': typeof CollegeRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/college/analytics': typeof CollegeAnalyticsRoute
  '/college/internships': typeof CollegeInternshipsRoute
  '/college/students': typeof CollegeStudentsRoute
  '/company/analytics': typeof CompanyAnalyticsRoute
  '/company/courses': typeof CompanyCoursesRoute
  '/company/interns': typeof CompanyInternsRoute
  '/company/opportunities': typeof CompanyOpportunitiesRoute
  '/company/students': typeof CompanyStudentsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/discover': typeof StudentDiscoverRoute
  '/student/internship': typeof StudentInternshipRoute
  '/student/learning': typeof StudentLearningRoute
  '/student/opportunities': typeof StudentOpportunitiesRouteWithChildren
  '/college/': typeof CollegeIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/opportunities/$id': typeof StudentOpportunitiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/college/analytics': typeof CollegeAnalyticsRoute
  '/college/internships': typeof CollegeInternshipsRoute
  '/college/students': typeof CollegeStudentsRoute
  '/company/analytics': typeof CompanyAnalyticsRoute
  '/company/courses': typeof CompanyCoursesRoute
  '/company/interns': typeof CompanyInternsRoute
  '/company/opportunities': typeof CompanyOpportunitiesRoute
  '/company/students': typeof CompanyStudentsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/discover': typeof StudentDiscoverRoute
  '/student/internship': typeof StudentInternshipRoute
  '/student/learning': typeof StudentLearningRoute
  '/student/opportunities': typeof StudentOpportunitiesRouteWithChildren
  '/college': typeof CollegeIndexRoute
  '/company': typeof CompanyIndexRoute
  '/student': typeof StudentIndexRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/opportunities/$id': typeof StudentOpportunitiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/college': typeof CollegeRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/college/analytics': typeof CollegeAnalyticsRoute
  '/college/internships': typeof CollegeInternshipsRoute
  '/college/students': typeof CollegeStudentsRoute
  '/company/analytics': typeof CompanyAnalyticsRoute
  '/company/courses': typeof CompanyCoursesRoute
  '/company/interns': typeof CompanyInternsRoute
  '/company/opportunities': typeof CompanyOpportunitiesRoute
  '/company/students': typeof CompanyStudentsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/discover': typeof StudentDiscoverRoute
  '/student/internship': typeof StudentInternshipRoute
  '/student/learning': typeof StudentLearningRoute
  '/student/opportunities': typeof StudentOpportunitiesRouteWithChildren
  '/college/': typeof CollegeIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/opportunities/$id': typeof StudentOpportunitiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/college'
    | '/company'
    | '/student'
    | '/college/analytics'
    | '/college/internships'
    | '/college/students'
    | '/company/analytics'
    | '/company/courses'
    | '/company/interns'
    | '/company/opportunities'
    | '/company/students'
    | '/student/applications'
    | '/student/discover'
    | '/student/internship'
    | '/student/learning'
    | '/student/opportunities'
    | '/college/'
    | '/company/'
    | '/student/'
    | '/student/courses/$id'
    | '/student/opportunities/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/college/analytics'
    | '/college/internships'
    | '/college/students'
    | '/company/analytics'
    | '/company/courses'
    | '/company/interns'
    | '/company/opportunities'
    | '/company/students'
    | '/student/applications'
    | '/student/discover'
    | '/student/internship'
    | '/student/learning'
    | '/student/opportunities'
    | '/college'
    | '/company'
    | '/student'
    | '/student/courses/$id'
    | '/student/opportunities/$id'
  id:
    | '__root__'
    | '/'
    | '/college'
    | '/company'
    | '/student'
    | '/college/analytics'
    | '/college/internships'
    | '/college/students'
    | '/company/analytics'
    | '/company/courses'
    | '/company/interns'
    | '/company/opportunities'
    | '/company/students'
    | '/student/applications'
    | '/student/discover'
    | '/student/internship'
    | '/student/learning'
    | '/student/opportunities'
    | '/college/'
    | '/company/'
    | '/student/'
    | '/student/courses/$id'
    | '/student/opportunities/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollegeRoute: typeof CollegeRouteWithChildren
  CompanyRoute: typeof CompanyRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college': {
      id: '/college'
      path: '/college'
      fullPath: '/college'
      preLoaderRoute: typeof CollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/company/': {
      id: '/company/'
      path: '/'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/college/': {
      id: '/college/'
      path: '/'
      fullPath: '/college/'
      preLoaderRoute: typeof CollegeIndexRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/student/opportunities': {
      id: '/student/opportunities'
      path: '/opportunities'
      fullPath: '/student/opportunities'
      preLoaderRoute: typeof StudentOpportunitiesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/learning': {
      id: '/student/learning'
      path: '/learning'
      fullPath: '/student/learning'
      preLoaderRoute: typeof StudentLearningRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/internship': {
      id: '/student/internship'
      path: '/internship'
      fullPath: '/student/internship'
      preLoaderRoute: typeof StudentInternshipRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/discover': {
      id: '/student/discover'
      path: '/discover'
      fullPath: '/student/discover'
      preLoaderRoute: typeof StudentDiscoverRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/applications': {
      id: '/student/applications'
      path: '/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof StudentApplicationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/company/students': {
      id: '/company/students'
      path: '/students'
      fullPath: '/company/students'
      preLoaderRoute: typeof CompanyStudentsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/opportunities': {
      id: '/company/opportunities'
      path: '/opportunities'
      fullPath: '/company/opportunities'
      preLoaderRoute: typeof CompanyOpportunitiesRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/interns': {
      id: '/company/interns'
      path: '/interns'
      fullPath: '/company/interns'
      preLoaderRoute: typeof CompanyInternsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/courses': {
      id: '/company/courses'
      path: '/courses'
      fullPath: '/company/courses'
      preLoaderRoute: typeof CompanyCoursesRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/analytics': {
      id: '/company/analytics'
      path: '/analytics'
      fullPath: '/company/analytics'
      preLoaderRoute: typeof CompanyAnalyticsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/college/students': {
      id: '/college/students'
      path: '/students'
      fullPath: '/college/students'
      preLoaderRoute: typeof CollegeStudentsRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/college/internships': {
      id: '/college/internships'
      path: '/internships'
      fullPath: '/college/internships'
      preLoaderRoute: typeof CollegeInternshipsRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/college/analytics': {
      id: '/college/analytics'
      path: '/analytics'
      fullPath: '/college/analytics'
      preLoaderRoute: typeof CollegeAnalyticsRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/student/opportunities/$id': {
      id: '/student/opportunities/$id'
      path: '/$id'
      fullPath: '/student/opportunities/$id'
      preLoaderRoute: typeof StudentOpportunitiesIdRouteImport
      parentRoute: typeof StudentOpportunitiesRoute
    }
    '/student/courses/$id': {
      id: '/student/courses/$id'
      path: '/courses/$id'
      fullPath: '/student/courses/$id'
      preLoaderRoute: typeof StudentCoursesIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface CollegeRouteChildren {
  CollegeAnalyticsRoute: typeof CollegeAnalyticsRoute
  CollegeInternshipsRoute: typeof CollegeInternshipsRoute
  CollegeStudentsRoute: typeof CollegeStudentsRoute
  CollegeIndexRoute: typeof CollegeIndexRoute
}

const CollegeRouteChildren: CollegeRouteChildren = {
  CollegeAnalyticsRoute: CollegeAnalyticsRoute,
  CollegeInternshipsRoute: CollegeInternshipsRoute,
  CollegeStudentsRoute: CollegeStudentsRoute,
  CollegeIndexRoute: CollegeIndexRoute,
}

const CollegeRouteWithChildren =
  CollegeRoute._addFileChildren(CollegeRouteChildren)

interface CompanyRouteChildren {
  CompanyAnalyticsRoute: typeof CompanyAnalyticsRoute
  CompanyCoursesRoute: typeof CompanyCoursesRoute
  CompanyInternsRoute: typeof CompanyInternsRoute
  CompanyOpportunitiesRoute: typeof CompanyOpportunitiesRoute
  CompanyStudentsRoute: typeof CompanyStudentsRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyAnalyticsRoute: CompanyAnalyticsRoute,
  CompanyCoursesRoute: CompanyCoursesRoute,
  CompanyInternsRoute: CompanyInternsRoute,
  CompanyOpportunitiesRoute: CompanyOpportunitiesRoute,
  CompanyStudentsRoute: CompanyStudentsRoute,
  CompanyIndexRoute: CompanyIndexRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

interface StudentOpportunitiesRouteChildren {
  StudentOpportunitiesIdRoute: typeof StudentOpportunitiesIdRoute
}

const StudentOpportunitiesRouteChildren: StudentOpportunitiesRouteChildren = {
  StudentOpportunitiesIdRoute: StudentOpportunitiesIdRoute,
}

const StudentOpportunitiesRouteWithChildren =
  StudentOpportunitiesRoute._addFileChildren(StudentOpportunitiesRouteChildren)

interface StudentRouteChildren {
  StudentApplicationsRoute: typeof StudentApplicationsRoute
  StudentDiscoverRoute: typeof StudentDiscoverRoute
  StudentInternshipRoute: typeof StudentInternshipRoute
  StudentLearningRoute: typeof StudentLearningRoute
  StudentOpportunitiesRoute: typeof StudentOpportunitiesRouteWithChildren
  StudentIndexRoute: typeof StudentIndexRoute
  StudentCoursesIdRoute: typeof StudentCoursesIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentApplicationsRoute: StudentApplicationsRoute,
  StudentDiscoverRoute: StudentDiscoverRoute,
  StudentInternshipRoute: StudentInternshipRoute,
  StudentLearningRoute: StudentLearningRoute,
  StudentOpportunitiesRoute: StudentOpportunitiesRouteWithChildren,
  StudentIndexRoute: StudentIndexRoute,
  StudentCoursesIdRoute: StudentCoursesIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollegeRoute: CollegeRouteWithChildren,
  CompanyRoute: CompanyRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
